[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
risk_oracle = "DMR3rXBh8RGrKyx1mxqFVTMbyfoiuu9iYHr6s6CW23ea"
mock_lender = "FkJrXyze9iFAmH7vUDtymAP3hzS3TaLAG16hQo6svv7p"

[programs.devnet]
risk_oracle = "DMR3rXBh8RGrKyx1mxqFVTMbyfoiuu9iYHr6s6CW23ea"
mock_lender = "FkJrXyze9iFAmH7vUDtymAP3hzS3TaLAG16hQo6svv7p"

[provider]
cluster = "Devnet"
wallet = "../updater/keypair.json"

[test]
startup_wait = 30000
skip_local_validator = true

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
